---
- hosts: localhost
  remote_user: root
  become: true

  vars:
    password: "root"

  tasks:

    - name: Add ppa:ondrej/php
      shell: apt-add-repository -y ppa:ondrej/php
    
    - name: 'Apt update'
      apt: update_cache=yes

    - name: Install Apache
      apt: package={{ item }} state=installed force=yes update_cache=yes
      with_items:
        - apache2

    - name: Install PHP 7.1
      apt: package={{ item }} state=installed force=yes update_cache=yes
      with_items:
        - php7.1
    
    - name: Disable some Apache2 Module
      shell: a2dismod {{ item }}
      with_items:
        - mpm_event
    
    - name: Enable Apache2 Module
      shell: a2enmod {{ item }}
      with_items:
        - mpm_prefork
        - php7.1
    
    - name: Set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{password | quote}}' vtype='password'

    - name: Confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{password | quote}}' vtype='password'
    
    - name: Install MySQL
      apt: package={{ item }} state=installed force=yes update_cache=yes
      with_items:
        - mysql-server
        - mysql-client
        - python-mysqldb
        - php7.1-mysql

    - name: Install PHPMyAdmin
      apt: package={{ item }} state=installed force=yes update_cache=yes
      with_items:
        - phpmyadmin
    
    - name: Move PHPMyAdmin to /phpmyadmin
      shell: ln -s /usr/share/phpmyadmin /var/www/html/ -f
    
    - name: Enable PHP Module
      shell: phpenmod {{ item }}
      with_items:
        - mcrypt
        - mbstring
    
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
